// AI recommendation per country, in plain words. Based on MultiBank_AI_Country_Timing_Strategy.html (August workbook, 10 September 2026).
// verdict: the one-line call. happened: what the figures show. action: what to do. timing: when to try it (ideas to test, not proven).
// "Paying customer" = a client who put money into a trading account.

export type Verdict = "Test carefully" | "Improve first" | "Check funding" | "Check records";
export type CountryRec = { verdict: Verdict; happened: string; action: string; timing: string; /** Shared "how" for the overview board: countries with the same text sit on one card. */ how: string };

export const AI_COUNTRY: Record<string, CountryRec> = {
  UAE: { verdict: "Test carefully", happened: "Google ads brought paying customers cheaper than Instagram and Facebook, and those customers put in more money.", action: "Double-check the numbers, then give Google ads a little more money and watch. Look at Instagram and Facebook on their own.", timing: "Evenings local time, Ramadan and Eid, and any day of the month when people tend to pay in.", how: "Give the winning ads a little more money and watch how many customers pay in." },
  Jordan: { verdict: "Test carefully", happened: "Instagram and Facebook brought paying customers at a low cost. We still need to confirm how many there were.", action: "Give Instagram and Facebook a little more money as a test. Add more only if the new customers are worth it.", timing: "Arabic learning sessions, weekdays, Ramadan and Eid.", how: "Give the winning ads a little more money and watch how many customers pay in." },
  KSA: { verdict: "Check funding", happened: "About $55,560 was spent. Google ads show no paying customers on record, and each one from Instagram and Facebook cost a lot.", action: "Find where people give up: signing up, proving who they are, or paying. Fix that step first.", timing: "Once fixed: pay days, local holidays, Ramadan and Eid.", how: "Find where people give up: signing up, proving who they are, or paying. Fix that step first." },
  Australia: { verdict: "Improve first", happened: "Both ad types brought paying customers. Instagram and Facebook did it cheaper than Google.", action: "Work out how much money each group of customers really brings in before moving any budget.", timing: "Australian hours and Australian summer holidays, not Europe's calendar.", how: "Work out how much money each group of customers really brings in before moving any budget." },
  Canada: { verdict: "Improve first", happened: "Instagram and Facebook customers cost a lot each. Google customers were cheaper but put in very little money.", action: "Check who these customers are and improve the weaker ads before spending more.", timing: "Canadian time zones, the right language, and working days.", how: "Find which ads bring good customers. Fix or cut the weak ones before spending more." },
  Germany: { verdict: "Check funding", happened: "Google ads brought paying customers. Instagram and Facebook show none on record.", action: "Check the Instagram and Facebook tracking and payments. Check whether the Google customers bring in enough money.", timing: "Office hours, school holidays, Easter and Christmas.", how: "Fix the Instagram and Facebook reporting, then check whether the Google customers bring in enough money." },
  Spain: { verdict: "Improve first", happened: "Both ad types cost a lot for each paying customer.", action: "Find which ads bring good customers. Fix or cut the weak ones.", timing: "Spanish-language ads, local hours and holiday seasons.", how: "Find which ads bring good customers. Fix or cut the weak ones before spending more." },
  Turkey: { verdict: "Improve first", happened: "Instagram and Facebook customers put in a lot of money each, but there were very few of them.", action: "Check how many customers made that result. Improve the paying step and the follow-up calls.", timing: "Turkish learning content, local holidays and big economic news days.", how: "Work out how much money each group of customers really brings in before moving any budget." },
  Morocco: { verdict: "Check funding", happened: "Instagram and Facebook leads were cheap, but cheap leads are not the same as paying customers. Google shows no paying customers on record.", action: "Check the quality of the leads and why Google customers are not paying in.", timing: "Arabic and French ads, local hours, Ramadan and Eid.", how: "Find where people give up: signing up, proving who they are, or paying. Fix that step first." },
  Tunisia: { verdict: "Improve first", happened: "Both ad types cost a lot for each paying customer, and the customers put in small amounts.", action: "Improve the ads and the sign-up steps before asking for more money.", timing: "Arabic and French ads, support hours, Ramadan and Eid.", how: "Find which ads bring good customers. Fix or cut the weak ones before spending more." },
  Lebanon: { verdict: "Improve first", happened: "Instagram and Facebook customers cost quite a lot each. Nobody has paid in a second time yet.", action: "Make signing up and paying easier. Look again after a longer period.", timing: "Support hours, pay days, Ramadan and Eid.", how: "Make signing up and paying easier, then look again after a longer period." },
  Oman: { verdict: "Check funding", happened: "Google ads show no paying customers on record. Instagram and Facebook customers cost a lot each.", action: "Check identity checks, failed payments and follow-up calls before adding money.", timing: "Working hours, known monthly patterns, local holidays.", how: "Find where people give up: signing up, proving who they are, or paying. Fix that step first." },
  Qatar: { verdict: "Check funding", happened: "Instagram and Facebook show no paying customers on record. Google customers cost a lot and put in little.", action: "Check the tracking and the payment steps. Keep extra spending on hold.", timing: "Support hours, known monthly patterns, Ramadan and Eid.", how: "Fix the Instagram and Facebook reporting, then check whether the Google customers bring in enough money." },
  India: { verdict: "Improve first", happened: "Google customers cost a lot each and put in small amounts.", action: "Check which product we may offer, who the customers are, and how they pay, before growing.", timing: "Selected local languages, Diwali and working hours.", how: "Find which ads bring good customers. Fix or cut the weak ones before spending more." },
  Pakistan: { verdict: "Check funding", happened: "Money was spent, but the report cannot say how many customers paid in.", action: "Find out whether anyone paid in. Then fix tracking, sign-up or payment problems.", timing: "Support hours, selected languages, Ramadan and Eid.", how: "Check the records and the tracking: find out whether data is missing or nobody paid in." },
  Greece: { verdict: "Check funding", happened: "Both ad types spent money, but no paying customers are on record.", action: "Find out whether the records are missing or people never paid in.", timing: "Greek-language ads, local hours and Orthodox Easter.", how: "Check the records and the tracking: find out whether data is missing or nobody paid in." },
  Kazakhstan: { verdict: "Check funding", happened: "Both ad types spent money, but no paying customers are on record.", action: "Check the records, the sign-up steps and the payment steps first.", timing: "Kazakh and Russian ads, weekdays and Nauryz.", how: "Check the records and the tracking: find out whether data is missing or nobody paid in." },
  Poland: { verdict: "Check funding", happened: "Both ad types spent money, but no paying customers are on record.", action: "Check how far people get and whether tracking works before adding money.", timing: "Polish-language ads, working days, Easter and Christmas.", how: "Check the records and the tracking: find out whether data is missing or nobody paid in." },
  Norway: { verdict: "Check funding", happened: "Both ad types spent money, but no paying customers are on record.", action: "Check whether leads turn into paying customers and where they stop.", timing: "The right languages, working days and summer holidays.", how: "Check the records and the tracking: find out whether data is missing or nobody paid in." },
  Sweden: { verdict: "Check funding", happened: "Both ad types spent money, but no paying customers are on record.", action: "Follow the customer's steps and fix any missing payment records.", timing: "The right languages, working days and summer holidays.", how: "Check the records and the tracking: find out whether data is missing or nobody paid in." },
  Netherlands: { verdict: "Check funding", happened: "Instagram and Facebook show no paying customers on record. Google customers cost a lot each.", action: "Fix the Instagram and Facebook reporting. Check whether Google brings good customers.", timing: "Dutch and English ads, local hours and holiday seasons.", how: "Fix the Instagram and Facebook reporting, then check whether the Google customers bring in enough money." },
  Switzerland: { verdict: "Check funding", happened: "Instagram and Facebook show no paying customers on record. Google customers cost a lot and put in little.", action: "Check both ad types before adding any money.", timing: "The customers' languages, local hours and local holidays.", how: "Fix the Instagram and Facebook reporting, then check whether the Google customers bring in enough money." },
  Syria: { verdict: "Improve first", happened: "Leads were cheap, but customers put in small amounts and the cost per paying customer needs a look.", action: "Confirm which product we may offer and how people can pay. Check what customers are worth before spending more.", timing: "Only for allowed campaigns: support hours and confirmed holidays.", how: "Work out how much money each group of customers really brings in before moving any budget." },
};

/** Note printed once on the section divider. */
export const AI_COUNTRY_NOTE = "“No paying customers on record” means the report shows zero. That may be missing data, late payments, or nobody paid in. Check before deciding. Every campaign must use a product and a MultiBank company that is allowed in that country.";
